import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { getPieceBySlug, getCategoryBySlug } from "@/lib/collection";
import { rooms } from "@/content/landing";
import { staticPieces } from "@/content/pieces";
import { statusLabel, priceLabel, periodRange } from "@/lib/format";
import PieceFigure from "@/components/piece/PieceFigure";
import ProvenanceDiagram from "@/components/piece/ProvenanceDiagram";
import EnquiryForm from "@/components/forms/EnquiryForm";
import InterestButton from "@/components/piece/InterestButton";
import RevealObserver from "@/components/scroll/RevealObserver";

export function generateStaticParams() {
  return staticPieces.map((p) => ({ slug: p.slug }));
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ slug: string }>;
}): Promise<Metadata> {
  const { slug } = await params;
  const piece = await getPieceBySlug(slug);
  if (!piece) return { title: "Piece" };
  // The per-piece Open Graph image is generated by the co-located
  // opengraph-image.tsx, so a link shared to Instagram or Pinterest lands with
  // this piece on the card. Metadata here supplies the title and description.
  return {
    title: piece.title,
    description: `${piece.attribution}. ${piece.story}`,
    openGraph: {
      title: `${piece.title}, Modern Life Furniture`,
      description: piece.attribution,
      type: "website",
    },
  };
}

export default async function PiecePage({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug } = await params;
  const piece = await getPieceBySlug(slug);
  if (!piece) notFound();

  const room = rooms.find((r) => r.slug === piece.categorySlug);
  const category = await getCategoryBySlug(piece.categorySlug);
  const visual = room?.visual ?? "rings";
  const canvasLabel = room?.canvasLabel ?? piece.title;

  return (
    <main className="page">
      <nav className="breadcrumb mono" aria-label="Breadcrumb">
        <Link href="/">Home</Link>
        <span aria-hidden="true">/</span>
        <Link href="/collection">Collection</Link>
        <span aria-hidden="true">/</span>
        <Link href={`/collection/${piece.categorySlug}`}>
          {category?.name ?? "Category"}
        </Link>
        <span aria-hidden="true">/</span>
        <span>{piece.title}</span>
      </nav>

      <div className="piece">
        <PieceFigure visual={visual} label={canvasLabel} images={piece.images} />

        <div className="piece-body">
          <span className="mono attribution">{piece.attribution}</span>
          <h1>{piece.title}</h1>
          {piece.provenanceVerified ? (
            <span
              className="seal"
              title="Provenance verified by Modern Life Furniture"
            >
              <span className="seal-mark" aria-hidden="true" />
              <span className="mono">Provenance verified</span>
            </span>
          ) : null}
          {piece.placeholder ? (
            <span className="mono" style={{ opacity: 0.55, display: "block", marginBottom: "1.4rem" }}>
              Placeholder listing, details to be confirmed
            </span>
          ) : null}
          <p className="story">{piece.story}</p>

          <div className="block">
            <span className="mono block-eyebrow">Specimen record</span>
            <dl>
              <dt>Attribution</dt>
              <dd>{piece.attribution}</dd>
              <dt>Period</dt>
              <dd>
                {periodRange(piece.periodLabel, piece.yearFrom, piece.yearTo)}
              </dd>
              <dt>Origin</dt>
              <dd>{piece.origin}</dd>
              <dt>Materials</dt>
              <dd>{piece.materials.join(", ")}</dd>
              <dt>Status</dt>
              <dd>{statusLabel(piece.status)}</dd>
              <dt>Price</dt>
              <dd>{priceLabel(piece.priceOnRequest, piece.pricePence)}</dd>
            </dl>
          </div>

          {piece.restorationNotes ? (
            <div className="block" style={{ marginTop: "1.4rem" }}>
              <span className="mono block-eyebrow">Restoration</span>
              <p>{piece.restorationNotes}</p>
            </div>
          ) : null}
        </div>
      </div>

      {piece.provenance.length > 0 ? (
        <section className="section-rule reveal" aria-label="Provenance">
          <span className="mono eyebrow">Provenance</span>
          <ProvenanceDiagram
            provenance={piece.provenance}
            label={`Provenance rings for the ${piece.title}`}
          />
        </section>
      ) : null}

      <section className="section-rule" aria-label="Acquire this piece">
        <span className="mono eyebrow">Acquire</span>

        <div className="acquire">
          <div className="acquire-head">
            <div className="acquire-price">
              <span className="mono acquire-label">Price</span>
              <span className="acquire-figure">
                {priceLabel(piece.priceOnRequest, piece.pricePence)}
              </span>
            </div>
            <div className="acquire-status" data-status={piece.status}>
              <span className="acquire-dot" aria-hidden="true" />
              <span className="mono">{statusLabel(piece.status)}</span>
            </div>
          </div>

          <p className="acquire-note">
            {piece.status === "sold"
              ? "This piece has been rehomed. Tell us what you are after and we will find its like, or register interest to hear when a similar piece arrives."
              : piece.status === "reserved"
                ? "This piece is reserved. Register interest and we will let you know if it becomes available again."
                : piece.status === "restoration"
                  ? "This piece is in restoration. Register interest to be told the moment it is ready, or send a note to ask about it."
                  : "To arrange a viewing, ask a question or begin an acquisition, send us a note below. For higher value pieces we handle the sale personally rather than through a checkout."}
          </p>

          <InterestButton pieceSlug={piece.slug} />
        </div>

        <div className="acquire-form">
          <span className="mono block-eyebrow">Send an enquiry</span>
          <EnquiryForm
            defaultKind="piece"
            pieceSlug={piece.slug}
            pieceTitle={piece.title}
          />
        </div>
      </section>

      <RevealObserver />
    </main>
  );
}
