import type { Metadata, Viewport } from "next";
import { fraunces, archivo, splineMono } from "./fonts";
import LenisProvider from "@/components/scroll/LenisProvider";
import Announcement from "@/components/chrome/Announcement";
import Header from "@/components/chrome/Header";
import Footer from "@/components/chrome/Footer";
import "./globals.css";

export const metadata: Metadata = {
  metadataBase: new URL("https://houseofchairs.co.uk"),
  title: {
    default: "House of Chairs, vintage designer furniture, chairs first",
    template: "%s, House of Chairs",
  },
  description:
    "Vintage designer furniture, chairs above all. Every piece one of one, checked, documented and delivered nationwide, sold by enquiry.",
  // The card itself is generated by app/opengraph-image.tsx and picked up
  // automatically, so the wordmark can never fall out of date behind a rebrand.
  openGraph: {
    title: "House of Chairs",
    description: "Vintage designer furniture, chairs first.",
    locale: "en_GB",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "House of Chairs",
    description: "Vintage designer furniture, chairs first.",
  },
};

export const viewport: Viewport = {
  themeColor: "#f5f3ef",
  colorScheme: "light",
};

/* Sitewide Organization JSON-LD, per the SEO rules in CLAUDE.md. Static and
   serialised once at build; per-piece Product JSON-LD lives on the piece
   page. */
const organisationJsonLd = {
  "@context": "https://schema.org",
  "@type": "Organization",
  name: "House of Chairs",
  url: "https://houseofchairs.co.uk",
  email: "sales@houseofchairs.co.uk",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en-GB"
      className={`${fraunces.variable} ${archivo.variable} ${splineMono.variable}`}
    >
      <body>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify(organisationJsonLd),
          }}
        />
        <noscript>
          <style>{`.reveal{opacity:1 !important;transform:none !important}`}</style>
        </noscript>
        <LenisProvider>
          {/* In normal flow under the fixed header, so it scrolls away and
              the header keeps the top of the viewport. */}
          <Announcement />
          <Header />
          {children}
          <Footer />
        </LenisProvider>
      </body>
    </html>
  );
}
